name: rxws
description: A lightweight, high-performance, pure Dart WebSocket client with full protocol control.
version: 1.1.1
homepage: https://github.com/msfm2018/rxws
repository: https://github.com/msfm2018/rxws
issue_tracker: https://github.com/msfm2018/rxws/issues

topics:
  - state-management
  - reactive
  - flutter-widgets
  - performance

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:



example: example/lib/main.dart